### ISSUE TITLE
Naming overlap

### ISSUE THREAD

**Issue by RoxanneSHS** [Argent77/A7-ImprovedArcher#3]
This mod and Song & Silence mod both add a kit named Sharpshooter for thieves
It is not noted as an incompatibility because both mods technically are compatible and do different things. Really the only problem seems to be the identical name (at least in English).
The best solution is to change the name of one of them.
Here are the details of what happens in a game
http://baldursextendedworld.com/Vanilla_Forums/discussion/649/thief-kit-2x-sharp-shooter-from-2-different-components-same-name-kit#latest

**Comment by Argent77** [comment]
I was aware of possible name collisions even when I came up with the kit. However, there are only so many names available that would be suitable for ranged-combat kits. Several other names I had to reject from the beginning because they were used more than once already. The situation is probably worse in other languages which don't have as many synonyms for ranged fighters.

Would adding a footnote to the kit description about the origin of the kit help?

**Comment by RoxanneSHS** [comment]
It was not an issue that I encountered myself but comes from discussion with another player. I will just relay your response and close the issue since you are aware of it already.

**Comment by Jeanpierregi** [comment]
Hi,

I was the one to notice this. 
I'm not a native english speaker so i'm not the best person to give names, but Sniper, Marksman, Member of the Marquis, even a simple "Shooter", ... Maybe those names were used in the other type of archers, but since I do not use it.


You can even use a "baldur's gate society" (from the forgotten realms) or whatever. Agent of Cyric or whatever is the association related to assassins...
Cleric are like that and it doesn't bother anyone, I guess.



A note in the kit is not useless at all, but it should be among the first thint to appear in description to have purpose, which is obviously not where you would want to put it to keep "logic" in the game description of each kit.

What is most bothering was that in the creation menu, there is (when both mods are installed) this:
XXX
XXX
Sharpshooter
Sharpshooter

When I saw this, I thought this was a bug and didn't even check the second one which was less powerful as a thief and better "archer". At the moment, I'm really not sure which is the one from your mod (I did the resesearch for the post RoxanneSHS provided) but it doesn't come instinctively because of the confusion with the name.

And both kits say almost the same, and only in the details are there differences.

Even a "ninja" name would be good for me because it would distinguish between both.
